### ISSUE TITLE
REISE.jl integration

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/REISE.jl#30]
It is time to integrate the REISE.jl engine to the simulation framework.

The user will be able when building a scenario to choose either REISE or REISE.jl as an engine. Here is a list of tasks that need to be completed:

- [x] install *Julia* on the server.
- [x] reorganize the PATH variables. There is a `const` modules  defined in  ***PreREISE*** and ***PostREISE*** and some of the variables therein are redundant.
- [x] move module across packages. The ***REISE*** and ***REISE.jl*** will each have a `call` and `extract_data` module and those won't be part of ***PreREISE*** and ***PostREISE***, respectively. Consequently, the latter packages will not be required anymore on the server to run and extract scenarios.
- [x] move `transferdata` from ***PostREISE*** to ***PowerSimData*** since data transfer (input and output) is done through the `Scenario` object which lives in ***PowerSimData***.
- [x] add a step in the scenario builder that sets the simulation engine:
- [x] add extra key (column) in the _info attribute of the `Scenario` object (*ScenarioList.csv*) that specifies the engine used (***REISE*** or ***REISE.jl***).
- [x] use the user specified engine when launching the simulation.
- [x] select the correct script when extracting the data on the server
